<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Emplist.aspx.cs" Inherits="emplist.Emplist" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
     <style type="text/css">
     .auto-style1 {
         height: 847px;
         position: absolute;
         left: 0px;
         top: -2px;
         width: 1732px;
     }
     .auto-style2 {
         margin-left: 22px;
     }
 </style>
  <link href="Content/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <form id="form1" runat="server">
        <div>
                      <div class="container-fluid" style="background-color: #FFCC66; padding-top: 20px; padding-bottom: 20px;">
            <div class="row text-center mb-4">
                <!-- Home Button -->
                <div class="col-auto">
                    <asp:Button ID="Button2" runat="server" Font-Bold="True" OnClick="Button2_Click" Text="Home" CssClass="btn btn-primary btn-lg" />
                </div>
                
                <!-- Employee List Button -->
                <div class="col-auto">
                    <asp:Button ID="Button3" runat="server" Font-Bold="True" Text="Employee List" OnClick="Button3_Click" CssClass="btn btn-success btn-lg" />
                </div>
                
                <!-- Name Button -->
                <div class="col-auto">
                    <asp:Button ID="Button4" runat="server" Font-Bold="True" Text="Name" CssClass="btn btn-info btn-lg" />
                </div>
                
                <!-- Logout Button -->
                <div class="col-auto">
                    <asp:Button ID="Button5" runat="server" Font-Bold="True" Text="Logout" OnClick="Button5_Click" CssClass="btn btn-danger btn-lg" />
                </div>
            </div>

            <!-- Employee List Title -->
            <div class="row mb-3">
                <div class="col text-center">
                    <asp:Label ID="Label1" runat="server" Font-Bold="True" Font-Underline="True" Text="Employee List" CssClass="h3"></asp:Label>
                </div>
            </div>

            <!-- Total Count Display -->
            <div class="row mb-4">
                <div class="col">
                    <label class="font-weight-bold">Total Count:</label>
                    <asp:Label ID="Label8" runat="server" Text="Label"></asp:Label>
                </div>
            </div>

            <!-- Create Employee Button -->
            <div class="row mb-4">
                <div class="col text-center">
                    <asp:Button ID="Button6" runat="server" Font-Bold="True" Text="Create Employee" OnClick="Button6_Click" CssClass="btn btn-warning btn-lg" />
                </div>
            </div>

            <!-- Search Section -->
            <div class="row mb-4">
                <div class="col-auto">
                    <asp:Button ID="Button7" runat="server" OnClick="Button7_Click" Text="Search" CssClass="btn btn-secondary" />
                </div>
                <div class="col-auto">
                    <asp:TextBox ID="TextBox4" runat="server" Font-Italic="True" Font-Size="Small" Width="309px" CssClass="form-control" Placeholder="Enter Search Keyword"></asp:TextBox>
                </div>
            </div>

            <!-- GridView for Employee List -->
            <div class="row mb-5">
                <div class="col">
                    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" BackColor="LightGoldenrodYellow" BorderColor="Tan" BorderWidth="1px" CellPadding="2" CssClass="table table-striped table-bordered" ForeColor="Black" GridLines="None" Height="350px" AutoGenerateDeleteButton="True" OnRowDeleting="GridView1_RowDeleting" OnRowEditing="GridView1_RowEditing" DataKeyNames="Id" BorderStyle="None" OnRowDataBound="GridView1_RowDataBound">
                        <AlternatingRowStyle BackColor="PaleGoldenrod" />
                        <Columns>
                            <asp:TemplateField HeaderText="Unique Id">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("Id") %>' class="form-control"></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label1" runat="server" Text='<%# Bind("Id") %>' class="form-control"></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Image">
                                <ItemTemplate>
                                    <asp:Image ID="Image1" runat="server" ImageUrl='<%# Eval("ImgUpload") %>' Width="100px" Height="100px" />
                                </ItemTemplate>
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox2" runat="server" Text='<%# Eval("ImgUpload") %>' class="form-control"></asp:TextBox>
                                </EditItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Name">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox3" runat="server" Text='<%# Bind("Name") %>' class="form-control"></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label2" runat="server" Text='<%# Bind("Name") %>' class="form-control"></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Email">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox9" runat="server" Text='<%# Bind("Email") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label8" runat="server" Text='<%# Bind("Email") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Mobile No">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox8" runat="server" Text='<%# Bind("MobileNo") %>' class="form-control"></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label7" runat="server" Text='<%# Bind("MobileNo") %>' class="form-control"></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                         
                              <asp:TemplateField HeaderText="Designation">
    <EditItemTemplate>
        <asp:DropDownList ID="DropDownList1" runat="server" CssClass="form-control">

           
        </asp:DropDownList>
    </EditItemTemplate>
    <ItemTemplate>
        <asp:Label ID="Label3" runat="server" Text='<%# Bind("Designation") %>' class="form-control"></asp:Label>
    </ItemTemplate>
</asp:TemplateField>

                         

                             <asp:TemplateField HeaderText="Gender">
            <EditItemTemplate>
                <asp:RadioButtonList ID="RadioButtonList1" runat="server" 
                    RepeatDirection="Horizontal" CssClass="form-control">
                    
                </asp:RadioButtonList>
            </EditItemTemplate>
            <ItemTemplate>
                <asp:Label ID="Label4" runat="server" Text='<%# Bind("Gender") %>' class="form-control"></asp:Label>
            </ItemTemplate>
        </asp:TemplateField>
                         


                             <asp:TemplateField HeaderText="Course">
            <EditItemTemplate>
                <asp:CheckBoxList ID="CheckBoxList1" runat="server" CssClass="form-control">
                    
                 
                </asp:CheckBoxList>
            </EditItemTemplate>
            <ItemTemplate>
                <asp:Label ID="Label5" runat="server" Text='<%# Bind("Course") %>' class="form-control"></asp:Label>
            </ItemTemplate>
        </asp:TemplateField>
                            <asp:TemplateField HeaderText="Created Date">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox7" runat="server" Text='<%# Bind("CreatedDate") %>' class="form-control"></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label6" runat="server" Text='<%# Bind("CreatedDate") %>' class="form-control"></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                        </Columns>
                        <FooterStyle BackColor="Tan" />
                        <HeaderStyle BackColor="Tan" Font-Bold="True" />
                        <PagerStyle BackColor="PaleGoldenrod" ForeColor="DarkSlateBlue" HorizontalAlign="Center" />
                        <SelectedRowStyle BackColor="DarkSlateBlue" ForeColor="GhostWhite" />
                    </asp:GridView>
                </div>
            </div>
        </div>
        </div>
    </form>
</body>
</html>
